### ISSUE TITLE
Please update dependencies and make a new release

### ISSUE THREAD

**Issue by igor-petruk** [Michael-F-Bryan/include_dir#43]
I was thinking of packaging this for Debian under https://salsa.debian.org/rust-team/debcargo-conf, but the dependencies are old and I have to package them first, which adds more work. It may be easier to just update deps here.

**Comment by Michael-F-Bryan** [comment]
[Done! :tada:](https://crates.io/crates/include_dir)

New dependencies:

```toml
# include_dir_impl/Cargo.toml

[dependencies]
proc-macro-hack = "0.5"
syn = "1"
quote = "1"
failure = "0.1"
proc-macro2 = "1"

# include_dir/Cargo.toml

[dependencies]
glob = "0.3"
proc-macro-hack = "0.5"
```
