### ISSUE TITLE
Enabling "glob" feature makes compilation fail on stable

### ISSUE THREAD

**Issue by aldanor** [Michael-F-Bryan/include_dir#70]
```rust
error[E0658]: `#[doc(cfg)]` is experimental
   --> .../include_dir-0.7.1/src/lib.rs:102:1
    |
102 | #[doc(cfg(feature = "glob"))]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I don't think you need it at all because since recently `#[cfg]` implies `#[doc(cfg)]` (https://github.com/rust-lang/rust/pull/89596).

Also, in some very rare cases when it may not work and you need to do it manually, you can do this:

- In `Cargo.toml`:
  ```toml
  [package.metadata.docs.rs]
  features = ["foo", "bar"]
  rustdoc-args = ["--cfg", "docsrs"]
  ```
- In `lib.rs`:
  ```rust
  #![cfg_attr(docsrs, feature(doc_cfg))]
  ```
- And then you can safely do:
  ```rust
  #[cfg_attr(docrs, doc(cfg(feature = "foo")))]
  ```
- And in order to build docs locally:
  ```sh
  RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --features foo,bar
  ```
